# This is a config for E2B sandbox template.
# You can use template ID (k0k6l9bi1sjd2ykz1kzk) or template name (v0-nextjs-build) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-nextjs-build") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-nextjs-build") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-nextjs-build')

team_id = "50db9a3f-d84d-4b74-a03e-138e16e16470"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-nextjs-build"
template_id = "k0k6l9bi1sjd2ykz1kzk"
